### ISSUE TITLE
considering the attack pattern in the code

### ISSUE THREAD

**Issue by byronxu89** [ShadowsocksR-Live/overtls#13]
do you handle tls network protocols appropriately. for example man-in-the-middle attack, replay attack,

**Comment by ssrlive** [comment]
As the goal of this software is to bypass GFW detection rather than various network attacks, once your traffic passes through GFW from the client to the server, the mission of this software is completed. As for the subsequent security work, this software is no longer responsible. Therefore, if you want to access your target website absolutely safely, please always use the HTTPS protocol for web access.

**Comment by ssrlive** [comment]
As the goal of OverTLS is to bypass GFW detection rather than resist various network attacks, once your traffic passes through GFW from the OverTLS client to the OverTLS server, the mission of OverTLS is completed. As for the subsequent security work, OverTLS is no longer responsible. Therefore, if you want to access your target website absolutely safely, please always use the HTTPS protocol for web connections.

As for your concerns about possible man-in-the-middle attacks and replay attacks between the OverTLS client and the OverTLS server, I believe the designers of the TLS protocol have already considered them for us, so we don't need to worry unnecessarily.

**Comment by byronxu89** [comment]
although tls protocol is validate by various formal methods in mathmatics, tls implementation is not always secure. If you does not handle tls inappropriately, it will be considered suspicious by GFW through active probing. GFW will check the error code and status code from server like authentication failure and authorization failure.

**Comment by ssrlive** [comment]
Let me tell you, shadowsocks is easy to be blocked just because its traffic characteristics do not belong to TLS.
